# Array of rules to ignore
ignored_rules: []
# Array of files for kubeconform to ignore
ignored_files: []
# Array of directories to be ignored under `config/kubernetes`
ignored_dirs: []
# Array of fragment paths of the deployment config for schema validations to ignore
ignored_deployment_config_fragments: []
# Set to true to enable auto-commits for the generation of kubernetes resources from kustomize
enable_kustomize_auto_commit: false
