name: Add Dependabot Core Maintainers as Reviewers

# **What it does**: Automatically add reviewers based on paths, for docs-internal and docs repos.
# **Why we have it**: So dependabot maintainers can be notified about relevant pull requests.
# **Who does it impact**: dependabot-updates-reviewers.

on:
  pull_request:
    paths:
      - 'data/reusable/dependabot/**'
      - 'content/code-security/dependabot/**'
      - 'content/rest/dependabot/**'

jobs:
  add-reviewer:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Add Dependabot Core Maintainers as reviewers
        env:
          GH_TOKEN: ${{ secrets.DOCS_BOT_PAT_WRITEORG_PROJECT }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          has_reviewer=$(
            gh pr view $PR --json reviews |
            jq 'any(.reviews[]; select(length > 0))'
          )
          if ! $has_reviewer
          then
            gh pr edit $PR --add-reviewer github/dependabot-updates-reviewers
          fi
